import Nav from "./(components)/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically since it's being imported above

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ticket App",
  description: "Generated by Furries",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col h-screen max-h-screen">
            <Nav session={session} />
            <div className="flex-grow overflow-y-auto bg-page text-default-text">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
